### PR TITLE
Add WASM/JS support via wasm-bindgen

### LINKED ISSUE #32: WIP: Add WASM/JS bindings via wasm-bindgen and example
Working on it and have something running that needs cleanup/completion

### PR DESCRIPTION
**Pull request by sdroege**
Fixes https://github.com/sdroege/ebur128/issues/32

Can be built with [`wasm-pack`](https://github.com/rustwasm/wasm-pack):
```sh
wasm-pack build --target web -- --features wasm
```

Example using this can be found here: https://coaxion.net/~slomo/ebur128-wasm/

TODO
  * [ ] CI integration
  * [ ] Tests

### CODE REVIEW

**Comment by sdroege** [comment]
Currently kind-of blocked by https://github.com/rustwasm/wasm-pack/issues/886

Workaround for now would be

```diff
diff --git a/Cargo.toml b/Cargo.toml
index bc79e90..e03ba85 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -60,6 +60,10 @@ version = "1.2.4"
 name = "ebur128"
 version = "1.2.4"
 
+[package.metadata.wasm-pack.profile.release]
+# See https://github.com/rustwasm/wasm-pack/issues/886
+wasm-opt = false
+
 [[bench]]
 name = "interp"
 harness = false
```

**Comment by wong2** [comment]
is it working now?

**Comment by sdroege** [comment]
> is it working now?

Yes, see https://coaxion.net/~slomo/ebur128-wasm/

I need to spend some time on cleaning this up and merging it though, see the TODO list in the initial commit.

**Comment by wong2** [comment]
great!

**Comment by sdroege** [comment]
If you want to help with that, please go ahead :)

**Pull request closed without merging**
